import type { CatalogItem } from './types'

/**
 * Catalogue Mini Déco — meubles & jouets chambre d’enfant
 * (inspiré IKEA kids / déco fille : lits, bureaux, Trofast, tipi, peluches…).
 */
export const CATALOG: CatalogItem[] = [
  // ── Existants Louise ─────────────────────────────────────
  {
    id: 'bed-louise',
    name: 'Lit Louise',
    category: 'beds',
    footprint: [2, 4],
    surfaceHeight: 0.68,
    visual: { type: 'primitive', kind: 'bedLouise', tint: '#F5F0EA' },
  },
  {
    id: 'stitch-blue',
    name: 'Stitch bleu',
    category: 'beds',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'plushStitch', tint: '#4A90D9' },
  },
  {
    id: 'angel-pink',
    name: 'Angel rose',
    category: 'beds',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'plushAngel', tint: '#F4A0BE' },
  },
  {
    id: 'desk-louise',
    name: 'Bureau Louise',
    category: 'desks',
    footprint: [2, 1],
    surfaceHeight: 0.72,
    visual: { type: 'primitive', kind: 'deskLouise', tint: '#F8F4EE' },
  },
  {
    id: 'chair-swivel-white',
    name: 'Chaise pivotante',
    category: 'desks',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'chairDesk', tint: '#F8F8F5' },
  },
  {
    id: 'lamp-rattan-gold',
    name: 'Lampe rotin doré',
    category: 'desks',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'lampRattan', tint: '#E8C898' },
  },
  {
    id: 'bookshelf-oak',
    name: 'Bibliothèque chêne',
    category: 'storage',
    footprint: [1, 1],
    surfaceHeight: 1.01,
    visual: { type: 'kenney', model: 'bookcaseOpen', tint: '#D4B896' },
  },
  {
    id: 'wardrobe-oak',
    name: 'Armoire chêne',
    category: 'storage',
    footprint: [2, 1],
    visual: { type: 'kenney', model: 'bookcaseClosedDoors', tint: '#C4A882' },
  },
  {
    id: 'trofast-low',
    name: 'Trofast bas',
    category: 'storage',
    footprint: [3, 1],
    surfaceHeight: 0.45,
    visual: { type: 'primitive', kind: 'trofast', tint: '#E8D4B8' },
  },
  {
    id: 'chest-lego-white',
    name: 'Coffre Lego blanc',
    category: 'storage',
    footprint: [2, 1],
    surfaceHeight: 0.49,
    visual: { type: 'kenney', model: 'cabinetBed', tint: '#F5F5F2' },
  },
  {
    id: 'basket-wicker-pompom',
    name: 'Panier osier pompons',
    category: 'storage',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'basket', tint: '#C4A882' },
  },
  {
    id: 'basket-wicker-small',
    name: 'Petit panier osier',
    category: 'storage',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'basket', tint: '#B8956A' },
  },
  {
    id: 'basket-oval-pink',
    name: 'Panier oval rose',
    category: 'storage',
    footprint: [2, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'basket', tint: '#F0A8C0' },
  },
  {
    id: 'dollhouse-white-grey',
    name: 'Grande maison de poupée',
    category: 'toys',
    footprint: [3, 2],
    visual: { type: 'primitive', kind: 'dollhouse', tint: '#F5F5F2' },
  },
  {
    id: 'lego-camper',
    name: 'Camping-car Lego',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'legoCamper', tint: '#F0F0EE' },
  },
  {
    id: 'lego-cluster',
    name: 'Village Lego',
    category: 'toys',
    footprint: [2, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'legoCluster', tint: '#E8C8D0' },
  },
  {
    id: 'pirate-ship-black',
    name: 'Bateau pirate',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'pirateShip', tint: '#2A2A2E' },
  },
  {
    id: 'camper-van-pink',
    name: 'Van rose',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'camperVan', tint: '#F0A0B8' },
  },
  {
    id: 'rug-hopscotch-pink',
    name: 'Tapis marelle rose',
    category: 'soft',
    footprint: [2, 3],
    surfaceHeight: 0.02,
    visual: { type: 'primitive', kind: 'rugHopscotch', tint: '#E8A0B0' },
  },
  {
    id: 'chair-rattan-child',
    name: 'Chaise rotin enfant',
    category: 'soft',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'chairRounded', tint: '#F0D040' },
  },
  {
    id: 'lightbox-louise',
    name: 'Lightbox Louise',
    category: 'decor',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'lightbox', tint: '#FAFAF8' },
  },

  // ── ~50 nouveaux ─────────────────────────────────────────
  // Beds
  {
    id: 'bed-white-simple',
    name: 'Lit blanc simple',
    category: 'beds',
    footprint: [2, 4],
    surfaceHeight: 0.42,
    visual: { type: 'kenney', model: 'bedSingle', tint: '#F8F8F5' },
  },
  {
    id: 'bed-canopy-pink',
    name: 'Lit baldaquin rose',
    category: 'beds',
    footprint: [2, 4],
    surfaceHeight: 0.3,
    visual: { type: 'primitive', kind: 'canopyBed', tint: '#F0A0B8' },
  },
  {
    id: 'bed-mint',
    name: 'Lit menthe',
    category: 'beds',
    footprint: [2, 3],
    surfaceHeight: 0.32,
    visual: { type: 'kenney', model: 'bedSingle', tint: '#A8D8C8' },
  },
  {
    id: 'mattress-floor',
    name: 'Matelas au sol',
    category: 'beds',
    footprint: [2, 3],
    surfaceHeight: 0.14,
    visual: { type: 'primitive', kind: 'floorMattress', tint: '#E8D8C8' },
  },
  {
    id: 'plush-bear-brown',
    name: 'Ours en peluche',
    category: 'beds',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'plushBear', tint: '#C4894A' },
  },
  {
    id: 'plush-unicorn-pink',
    name: 'Licorne rose',
    category: 'beds',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'plushUnicorn', tint: '#F8D0E8' },
  },
  {
    id: 'plush-dino-green',
    name: 'Dino vert',
    category: 'beds',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'plushDino', tint: '#7EC070' },
  },
  {
    id: 'plush-bunny-cream',
    name: 'Lapin crème',
    category: 'beds',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'plush', tint: '#F5EDE0' },
  },

  // Desks
  {
    id: 'desk-white-kids',
    name: 'Bureau blanc enfant',
    category: 'desks',
    footprint: [2, 1],
    surfaceHeight: 0.45,
    visual: { type: 'kenney', model: 'desk', tint: '#F8F8F5' },
  },
  {
    id: 'desk-oak-small',
    name: 'Petit bureau chêne',
    category: 'desks',
    footprint: [2, 1],
    surfaceHeight: 0.45,
    visual: { type: 'kenney', model: 'desk', tint: '#D4B896' },
  },
  {
    id: 'stool-wood',
    name: 'Tabouret bois',
    category: 'desks',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'stoolBar', tint: '#F0D040' },
  },
  {
    id: 'chair-kids-yellow',
    name: 'Chaise jaune',
    category: 'desks',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'chair', tint: '#F0D040' },
  },
  {
    id: 'easel-paint',
    name: 'Chevalet peinture',
    category: 'desks',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'easel', tint: '#C9A66B' },
  },
  {
    id: 'lamp-desk-white',
    name: 'Lampe de bureau',
    category: 'desks',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'lampSquareTable', tint: '#F8F8F5' },
  },
  {
    id: 'crayon-box',
    name: 'Boîte de crayons',
    category: 'desks',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'crayonBox', tint: '#E8A040' },
  },
  {
    id: 'books-stack-desk',
    name: 'Pile de livres',
    category: 'desks',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'books', tint: '#70A0D0' },
  },

  // Storage
  {
    id: 'nightstand-white',
    name: 'Table de nuit',
    category: 'storage',
    footprint: [1, 1],
    surfaceHeight: 0.33,
    visual: { type: 'kenney', model: 'sideTableDrawers', tint: '#F8F4EE' },
  },
  {
    id: 'nightstand-pink',
    name: 'Table de nuit rose',
    category: 'storage',
    footprint: [1, 1],
    surfaceHeight: 0.33,
    visual: { type: 'kenney', model: 'sideTable', tint: '#F0A0B8' },
  },
  {
    id: 'dresser-rose',
    name: 'Commode rose',
    category: 'storage',
    footprint: [2, 1],
    surfaceHeight: 0.35,
    visual: { type: 'kenney', model: 'cabinetTelevisionDoors', tint: '#E890A0' },
  },
  {
    id: 'dresser-white',
    name: 'Commode blanche',
    category: 'storage',
    footprint: [2, 1],
    surfaceHeight: 0.35,
    visual: { type: 'kenney', model: 'cabinetTelevisionDoors', tint: '#F5F5F2' },
  },
  {
    id: 'shelf-low-white',
    name: 'Étagère basse',
    category: 'storage',
    footprint: [2, 1],
    surfaceHeight: 0.74,
    visual: { type: 'kenney', model: 'bookcaseOpenLow', tint: '#E8E0D8' },
  },
  {
    id: 'trofast-tall',
    name: 'Trofast haut',
    category: 'storage',
    footprint: [2, 1],
    surfaceHeight: 0.9,
    visual: { type: 'primitive', kind: 'trofast', tint: '#F0E4D4' },
  },
  {
    id: 'toy-chest-yellow',
    name: 'Coffre à jouets',
    category: 'storage',
    footprint: [2, 1],
    surfaceHeight: 0.55,
    visual: { type: 'kenney', model: 'cardboardBoxClosed', tint: '#F0C040' },
  },
  {
    id: 'laundry-hamper',
    name: 'Panier à linge',
    category: 'storage',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'laundryHamper', tint: '#E8D0A8' },
  },
  {
    id: 'basket-mint',
    name: 'Panier menthe',
    category: 'storage',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'basket', tint: '#A8D8C8' },
  },
  {
    id: 'basket-sky',
    name: 'Panier ciel',
    category: 'storage',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'basket', tint: '#A8D0E8' },
  },
  {
    id: 'wardrobe-white',
    name: 'Armoire blanche',
    category: 'storage',
    footprint: [2, 1],
    visual: { type: 'kenney', model: 'bookcaseClosedWide', tint: '#D4B896' },
  },
  {
    id: 'bookshelf-white',
    name: 'Bibliothèque blanche',
    category: 'storage',
    footprint: [1, 1],
    surfaceHeight: 1.01,
    visual: { type: 'kenney', model: 'bookcaseOpen', tint: '#D4B896' },
  },

  // Toys
  {
    id: 'teepee-mint',
    name: 'Tipi menthe',
    category: 'toys',
    footprint: [2, 2],
    visual: { type: 'primitive', kind: 'teepee', tint: '#A8D8C8' },
  },
  {
    id: 'play-tent-coral',
    name: 'Tente de jeu',
    category: 'toys',
    footprint: [2, 2],
    visual: { type: 'primitive', kind: 'playTent', tint: '#FF8B7B' },
  },
  {
    id: 'rocking-horse',
    name: 'Cheval à bascule',
    category: 'toys',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'rockingHorse', tint: '#E8A0B0' },
  },
  {
    id: 'toy-kitchen-pink',
    name: 'Cuisine jouet',
    category: 'toys',
    footprint: [2, 1],
    surfaceHeight: 0.45,
    visual: { type: 'kenney', model: 'kitchenCabinet', tint: '#F0A0B8' },
  },
  {
    id: 'train-wood',
    name: 'Train en bois',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'trainSet', tint: '#E07070' },
  },
  {
    id: 'scooter-pink',
    name: 'Trottinette rose',
    category: 'toys',
    footprint: [1, 2],
    visual: { type: 'primitive', kind: 'scooter', tint: '#F0A0B8' },
  },
  {
    id: 'ball-pink',
    name: 'Ballon rose',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'ball', tint: '#F080A0' },
  },
  {
    id: 'ball-yellow',
    name: 'Ballon jaune',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'ball', tint: '#F0D040' },
  },
  {
    id: 'doll-pram',
    name: 'Poussette poupée',
    category: 'toys',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'dollPram', tint: '#F0A0B8' },
  },
  {
    id: 'xylophone-rainbow',
    name: 'Xylophone',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'xylophone', tint: '#C9A66B' },
  },
  {
    id: 'blocks-abc',
    name: 'Cubes ABC',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'blocks', tint: '#E07070' },
  },
  {
    id: 'toy-robot',
    name: 'Robot jouet',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'toy', tint: '#70A0D0' },
  },
  {
    id: 'toy-car-red',
    name: 'Voiture rouge',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'camperVan', tint: '#E05050' },
  },
  {
    id: 'lego-house-pink',
    name: 'Maison Lego rose',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'legoCluster', tint: '#F0C0D0' },
  },

  // Soft
  {
    id: 'pouf-pink',
    name: 'Pouf rose',
    category: 'soft',
    footprint: [1, 1],
    surfaceHeight: 0.22,
    visual: { type: 'kenney', model: 'loungeSofaOttoman', tint: '#F0A0B8' },
  },
  {
    id: 'pouf-mint',
    name: 'Pouf menthe',
    category: 'soft',
    footprint: [1, 1],
    surfaceHeight: 0.22,
    visual: { type: 'kenney', model: 'loungeSofaOttoman', tint: '#A8D8C8' },
  },
  {
    id: 'beanbag-coral',
    name: 'Poufle corail',
    category: 'soft',
    footprint: [2, 2],
    surfaceHeight: 0.28,
    visual: { type: 'primitive', kind: 'beanbag', tint: '#F08070' },
  },
  {
    id: 'rug-round-yellow',
    name: 'Tapis rond jaune',
    category: 'soft',
    footprint: [2, 2],
    surfaceHeight: 0.02,
    visual: { type: 'kenney', model: 'rugRound', tint: '#F0D040' },
  },
  {
    id: 'rug-cloud',
    name: 'Tapis nuage',
    category: 'soft',
    footprint: [2, 2],
    surfaceHeight: 0.02,
    visual: { type: 'kenney', model: 'rugRounded', tint: '#E8F0F8' },
  },
  {
    id: 'rug-mint-large',
    name: 'Grand tapis menthe',
    category: 'soft',
    footprint: [3, 2],
    surfaceHeight: 0.02,
    visual: { type: 'kenney', model: 'rugRectangle', tint: '#A8D8C8' },
  },
  {
    id: 'chair-soft-lilac',
    name: 'Fauteuil lilas',
    category: 'soft',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'chairCushion', tint: '#C8A0D8' },
  },

  // Decor
  {
    id: 'plant-monstera',
    name: 'Plante monstera',
    category: 'decor',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'pottedPlant', tint: '#5A9E5A' },
  },
  {
    id: 'plant-cactus',
    name: 'Petit cactus',
    category: 'decor',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'plantSmall2', tint: '#7EC070' },
  },
  {
    id: 'floor-lamp-cream',
    name: 'Lampadaire',
    category: 'decor',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'floorLamp', tint: '#F5EDE0' },
  },
  {
    id: 'night-light-moon',
    name: 'Veilleuse lune',
    category: 'decor',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'nightLight', tint: '#FFE8B0' },
  },
  {
    id: 'night-light-star',
    name: 'Veilleuse étoile',
    category: 'decor',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'nightLight', tint: '#C8E0FF' },
  },
  {
    id: 'globe-earth',
    name: 'Globe terrestre',
    category: 'decor',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'globe', tint: '#5B9FCF' },
  },
  {
    id: 'mirror-round',
    name: 'Miroir rond',
    category: 'decor',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'mirror', tint: '#E8D8C8' },
  },
  {
    id: 'frame-photo-pink',
    name: 'Cadre photo',
    category: 'decor',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'photoFrame', tint: '#F0A0B8' },
  },

  // ── Animaux (chambre + jardin) ───────────────────────────
  {
    id: 'cat-devon-rex',
    name: 'Chat Devon Rex',
    category: 'animals',
    footprint: [1, 1],
    nestable: true,
    outdoor: true,
    visual: { type: 'primitive', kind: 'animalDevonRex', tint: '#2A2A32' },
  },
  {
    id: 'dog-puppy-gold',
    name: 'Chiot doré',
    category: 'animals',
    footprint: [1, 1],
    nestable: true,
    outdoor: true,
    visual: { type: 'primitive', kind: 'animalPuppy', tint: '#F0B060' },
  },
  {
    id: 'rabbit-white',
    name: 'Lapin blanc',
    category: 'animals',
    footprint: [1, 1],
    nestable: true,
    outdoor: true,
    visual: { type: 'primitive', kind: 'animalRabbit', tint: '#FFFAF5' },
  },
  {
    id: 'duck-yellow',
    name: 'Canard jaune',
    category: 'animals',
    footprint: [1, 1],
    nestable: true,
    outdoor: true,
    visual: { type: 'primitive', kind: 'animalDuck', tint: '#FFE040' },
  },
  {
    id: 'hedgehog-brown',
    name: 'Hérisson',
    category: 'animals',
    footprint: [1, 1],
    nestable: true,
    outdoor: true,
    visual: { type: 'primitive', kind: 'animalHedgehog', tint: '#A06828' },
  },
  {
    id: 'frog-green',
    name: 'Grenouille',
    category: 'animals',
    footprint: [1, 1],
    nestable: true,
    outdoor: true,
    visual: { type: 'primitive', kind: 'animalFrog', tint: '#4CB86A' },
  },
  {
    id: 'bird-blue',
    name: 'Oiseau bleu',
    category: 'animals',
    footprint: [1, 1],
    nestable: true,
    outdoor: true,
    visual: { type: 'primitive', kind: 'animalBird', tint: '#4AA0F0' },
  },

  // ── Vague stylée (+50) ───────────────────────────────────
  // Soft seating
  {
    id: 'sofa-blush',
    name: 'Canapé blush',
    category: 'soft',
    footprint: [3, 2],
    surfaceHeight: 0.42,
    visual: { type: 'kenney', model: 'loungeSofa', tint: '#F0A0B8' },
  },
  {
    id: 'sofa-long-cream',
    name: 'Canapé long crème',
    category: 'soft',
    footprint: [4, 2],
    surfaceHeight: 0.4,
    visual: { type: 'kenney', model: 'loungeSofaLong', tint: '#F5F0EA' },
  },
  {
    id: 'sofa-corner-mint',
    name: 'Canapé angle menthe',
    category: 'soft',
    footprint: [3, 3],
    surfaceHeight: 0.42,
    visual: { type: 'kenney', model: 'loungeSofaCorner', tint: '#A8D8C8' },
  },
  {
    id: 'lounge-chair-rose',
    name: 'Fauteuil rose',
    category: 'soft',
    footprint: [2, 2],
    surfaceHeight: 0.42,
    visual: { type: 'kenney', model: 'loungeChair', tint: '#E890A0' },
  },
  {
    id: 'lounge-relax-lilac',
    name: 'Fauteuil relax lilas',
    category: 'soft',
    footprint: [2, 2],
    surfaceHeight: 0.42,
    visual: { type: 'kenney', model: 'loungeChairRelax', tint: '#C8A0D8' },
  },
  {
    id: 'bench-cushion-pink',
    name: 'Banc coussin rose',
    category: 'soft',
    footprint: [2, 1],
    surfaceHeight: 0.45,
    visual: { type: 'kenney', model: 'benchCushion', tint: '#F0A0B8' },
  },
  {
    id: 'bench-low-mint',
    name: 'Banc bas menthe',
    category: 'soft',
    footprint: [2, 1],
    surfaceHeight: 0.22,
    visual: { type: 'kenney', model: 'benchCushionLow', tint: '#A8D8C8' },
  },
  {
    id: 'bench-wood-oak',
    name: 'Banc bois chêne',
    category: 'soft',
    footprint: [2, 1],
    surfaceHeight: 0.45,
    visual: { type: 'kenney', model: 'bench', tint: '#D4B896' },
  },

  // Tables
  {
    id: 'coffee-table-oak',
    name: 'Table basse chêne',
    category: 'soft',
    footprint: [2, 2],
    surfaceHeight: 0.32,
    visual: { type: 'kenney', model: 'tableCoffee', tint: '#D4B896' },
  },
  {
    id: 'coffee-table-glass',
    name: 'Table basse verre',
    category: 'soft',
    footprint: [2, 2],
    surfaceHeight: 0.32,
    visual: { type: 'kenney', model: 'tableCoffeeGlass', tint: '#E8F0F8' },
  },
  {
    id: 'coffee-square-white',
    name: 'Table basse blanche',
    category: 'soft',
    footprint: [2, 2],
    surfaceHeight: 0.32,
    visual: { type: 'kenney', model: 'tableCoffeeSquare', tint: '#F8F8F5' },
  },
  {
    id: 'table-round-kids',
    name: 'Table ronde enfants',
    category: 'desks',
    footprint: [2, 2],
    surfaceHeight: 0.42,
    visual: { type: 'kenney', model: 'tableRound', tint: '#F0D040' },
  },
  {
    id: 'table-play-cloth',
    name: 'Table nappe fleurie',
    category: 'desks',
    footprint: [2, 2],
    surfaceHeight: 0.42,
    visual: { type: 'kenney', model: 'tableCloth', tint: '#F0A0B8' },
  },
  {
    id: 'table-cross-pink',
    name: 'Table croisée rose',
    category: 'desks',
    footprint: [2, 2],
    surfaceHeight: 0.42,
    visual: { type: 'kenney', model: 'tableCross', tint: '#F0A0B8' },
  },
  {
    id: 'desk-corner-white',
    name: 'Bureau d’angle blanc',
    category: 'desks',
    footprint: [2, 2],
    surfaceHeight: 0.36,
    visual: { type: 'kenney', model: 'deskCorner', tint: '#F8F8F5' },
  },

  // Beds & storage
  {
    id: 'bed-bunk-pink',
    name: 'Lits superposés rose',
    category: 'beds',
    footprint: [2, 4],
    surfaceHeight: 0.55,
    visual: { type: 'kenney', model: 'bedBunk', tint: '#F0A0B8' },
  },
  {
    id: 'cabinet-drawer-cream',
    name: 'Meuble tiroirs crème',
    category: 'storage',
    footprint: [1, 1],
    surfaceHeight: 0.45,
    visual: { type: 'kenney', model: 'cabinetBedDrawer', tint: '#F5F0EA' },
  },
  {
    id: 'cabinet-drawer-table',
    name: 'Table de chevet tiroirs',
    category: 'storage',
    footprint: [1, 1],
    surfaceHeight: 0.45,
    visual: { type: 'kenney', model: 'cabinetBedDrawerTable', tint: '#F8F8F5' },
  },
  {
    id: 'tv-cabinet-oak',
    name: 'Meuble TV chêne',
    category: 'storage',
    footprint: [2, 1],
    surfaceHeight: 0.4,
    visual: { type: 'kenney', model: 'cabinetTelevision', tint: '#D4B896' },
  },
  {
    id: 'bookcase-closed-oak',
    name: 'Bibliothèque fermée',
    category: 'storage',
    footprint: [1, 1],
    surfaceHeight: 1.2,
    visual: { type: 'kenney', model: 'bookcaseClosed', tint: '#D4B896' },
  },
  {
    id: 'coat-rack-standing',
    name: 'Porte-manteau',
    category: 'storage',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'coatRackStanding', tint: '#D4B896' },
  },
  {
    id: 'coat-rack-wall',
    name: 'Patère murale',
    category: 'storage',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'coatRack', tint: '#F0A0B8' },
  },
  {
    id: 'stool-square-yellow',
    name: 'Tabouret carré jaune',
    category: 'desks',
    footprint: [1, 1],
    surfaceHeight: 0.55,
    visual: { type: 'kenney', model: 'stoolBarSquare', tint: '#F0D040' },
  },
  {
    id: 'trash-pastel',
    name: 'Poubelle pastel',
    category: 'storage',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'trashcan', tint: '#A8D8C8' },
  },

  // Lights & media
  {
    id: 'floor-lamp-square',
    name: 'Lampadaire carré',
    category: 'decor',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'lampSquareFloor', tint: '#F5F0EA' },
  },
  {
    id: 'radio-retro-pink',
    name: 'Radio rétro rose',
    category: 'decor',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'radio', tint: '#F0A0B8' },
  },
  {
    id: 'tv-vintage-cream',
    name: 'Télé vintage',
    category: 'decor',
    footprint: [2, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'televisionVintage', tint: '#F5F0EA' },
  },
  {
    id: 'tv-modern-lilac',
    name: 'Télé moderne',
    category: 'decor',
    footprint: [2, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'televisionModern', tint: '#C8A0D8' },
  },
  {
    id: 'speaker-mini-pink',
    name: 'Enceinte mini',
    category: 'decor',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'speakerSmall', tint: '#F0A0B8' },
  },
  {
    id: 'speaker-tall',
    name: 'Enceinte haute',
    category: 'decor',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'speaker', tint: '#2A2A32' },
  },

  // Plants
  {
    id: 'plant-fern',
    name: 'Fougère',
    category: 'decor',
    footprint: [1, 1],
    outdoor: true,
    visual: { type: 'kenney', model: 'plantSmall1', tint: '#5A9E5A' },
  },
  {
    id: 'plant-succulent',
    name: 'Succulente',
    category: 'decor',
    footprint: [1, 1],
    nestable: true,
    outdoor: true,
    visual: { type: 'kenney', model: 'plantSmall3', tint: '#7EC070' },
  },

  // Desk gadgets (nestable)
  {
    id: 'laptop-blush',
    name: 'Laptop blush',
    category: 'desks',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'laptop', tint: '#F0A0B8' },
  },
  {
    id: 'keyboard-white',
    name: 'Clavier blanc',
    category: 'desks',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'computerKeyboard', tint: '#F8F8F5' },
  },
  {
    id: 'mouse-pink',
    name: 'Souris rose',
    category: 'desks',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'computerMouse', tint: '#F0A0B8' },
  },
  {
    id: 'screen-desk',
    name: 'Écran bureau',
    category: 'desks',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'computerScreen', tint: '#2A2A32' },
  },

  // Toy kitchen extras
  {
    id: 'fridge-toy-pink',
    name: 'Frigo jouet rose',
    category: 'toys',
    footprint: [1, 1],
    surfaceHeight: 0.55,
    visual: { type: 'kenney', model: 'kitchenFridgeSmall', tint: '#F0A0B8' },
  },
  {
    id: 'microwave-toy',
    name: 'Micro-ondes jouet',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'kitchenMicrowave', tint: '#F8F8F5' },
  },
  {
    id: 'coffee-machine-toy',
    name: 'Machine à café jouet',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'kitchenCoffeeMachine', tint: '#E890A0' },
  },
  {
    id: 'blender-toy',
    name: 'Blender jouet',
    category: 'toys',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'kitchenBlender', tint: '#7EC8E8' },
  },
  {
    id: 'washer-toy',
    name: 'Machine à laver jouet',
    category: 'toys',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'washer', tint: '#A8D0E8' },
  },

  // Rugs
  {
    id: 'rug-square-lilac',
    name: 'Tapis carré lilas',
    category: 'soft',
    footprint: [2, 2],
    surfaceHeight: 0.02,
    visual: { type: 'kenney', model: 'rugSquare', tint: '#C8A0D8' },
  },

  // Stylish custom primitives
  {
    id: 'vanity-pink',
    name: 'Coiffeuse rose',
    category: 'desks',
    footprint: [2, 1],
    surfaceHeight: 0.74,
    visual: { type: 'primitive', kind: 'vanityPink', tint: '#F0A0B8' },
  },
  {
    id: 'star-mobile',
    name: 'Mobile étoiles',
    category: 'decor',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'starMobile', tint: '#F0D040' },
  },
  {
    id: 'mushroom-lamp',
    name: 'Lampe champignon',
    category: 'decor',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'mushroomLamp', tint: '#FF6B8A' },
  },
  {
    id: 'rainbow-shelf',
    name: 'Étagère arc-en-ciel',
    category: 'storage',
    footprint: [2, 1],
    surfaceHeight: 0.59,
    visual: { type: 'primitive', kind: 'rainbowShelf', tint: '#F07070' },
  },
  {
    id: 'music-box-ballerina',
    name: 'Boîte à musique',
    category: 'decor',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'musicBox', tint: '#E890B0' },
  },
  {
    id: 'fairy-lights',
    name: 'Guirlande magique',
    category: 'decor',
    footprint: [1, 1],
    outdoor: true,
    visual: { type: 'primitive', kind: 'fairyLights', tint: '#FFE8A0' },
  },
  {
    id: 'toy-castle-pink',
    name: 'Château princesse',
    category: 'toys',
    footprint: [2, 1],
    visual: { type: 'primitive', kind: 'toyCastle', tint: '#F0A0B8' },
  },
  {
    id: 'dreamcatcher-stand',
    name: 'Attrape-rêves',
    category: 'decor',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'dreamcatcher', tint: '#C8A0E8' },
  },
  {
    id: 'toy-slide-coral',
    name: 'Toboggan corail',
    category: 'toys',
    footprint: [2, 1],
    outdoor: true,
    visual: { type: 'primitive', kind: 'toySlide', tint: '#FF8B7B' },
  },
  {
    id: 'garden-swing',
    name: 'Balançoire jardin',
    category: 'toys',
    footprint: [2, 1],
    outdoor: true,
    visual: { type: 'primitive', kind: 'gardenSwing', tint: '#F0A0B8' },
  },
  {
    id: 'mini-trampoline',
    name: 'Mini trampoline',
    category: 'toys',
    footprint: [2, 2],
    outdoor: true,
    visual: { type: 'primitive', kind: 'miniTrampoline', tint: '#70A0E0' },
  },
  {
    id: 'cloud-shelf',
    name: 'Étagère nuage',
    category: 'storage',
    footprint: [2, 1],
    surfaceHeight: 0.45,
    visual: { type: 'primitive', kind: 'cloudShelf', tint: '#A8D0E8' },
  },

  // ── Vague salle de bain / cuisine / douillet (Kenney + custom) ──
  {
    id: 'bathtub-blush',
    name: 'Baignoire blush',
    category: 'toys',
    footprint: [2, 1],
    surfaceHeight: 0.42,
    visual: { type: 'kenney', model: 'bathtub', tint: '#F0A0B8' },
  },
  {
    id: 'shower-sky',
    name: 'Douche ciel',
    category: 'toys',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'shower', tint: '#A8D0E8' },
  },
  {
    id: 'toilet-cream',
    name: 'Toilettes crème',
    category: 'toys',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'toilet', tint: '#F8F8F5' },
  },
  {
    id: 'sink-bathroom-mint',
    name: 'Lavabo menthe',
    category: 'toys',
    footprint: [1, 1],
    surfaceHeight: 0.82,
    visual: { type: 'kenney', model: 'bathroomSink', tint: '#A8D8C8' },
  },
  {
    id: 'cabinet-bathroom-cream',
    name: 'Meuble lavabo crème',
    category: 'storage',
    footprint: [1, 1],
    surfaceHeight: 0.78,
    visual: { type: 'kenney', model: 'bathroomCabinet', tint: '#F5F0EA' },
  },
  {
    id: 'mirror-bathroom',
    name: 'Miroir salle de bain',
    category: 'decor',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'bathroomMirror', tint: '#E8F0F8' },
  },
  {
    id: 'dryer-sky',
    name: 'Sèche-linge ciel',
    category: 'toys',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'dryer', tint: '#A8D0E8' },
  },
  {
    id: 'washer-dryer-stack',
    name: 'Lave-linge + sèche-linge',
    category: 'toys',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'washerDryerStacked', tint: '#C8D8E8' },
  },
  {
    id: 'stove-electric-pink',
    name: 'Cuisinière rose',
    category: 'toys',
    footprint: [1, 1],
    surfaceHeight: 0.85,
    visual: { type: 'kenney', model: 'kitchenStoveElectric', tint: '#F0A0B8' },
  },
  {
    id: 'sink-kitchen-sky',
    name: 'Évier cuisine ciel',
    category: 'toys',
    footprint: [2, 1],
    surfaceHeight: 0.88,
    visual: { type: 'kenney', model: 'kitchenSink', tint: '#A8D0E8' },
  },
  {
    id: 'fridge-tall-cream',
    name: 'Grand frigo crème',
    category: 'toys',
    footprint: [1, 1],
    surfaceHeight: 0.95,
    visual: { type: 'kenney', model: 'kitchenFridge', tint: '#F5F0EA' },
  },
  {
    id: 'kitchen-bar-oak',
    name: 'Bar cuisine chêne',
    category: 'desks',
    footprint: [2, 1],
    surfaceHeight: 0.9,
    visual: { type: 'kenney', model: 'kitchenBar', tint: '#D4B896' },
  },
  {
    id: 'kitchen-bar-end',
    name: 'Bout de bar',
    category: 'desks',
    footprint: [1, 1],
    surfaceHeight: 0.9,
    visual: { type: 'kenney', model: 'kitchenBarEnd', tint: '#D4B896' },
  },
  {
    id: 'cabinet-drawer-kitchen',
    name: 'Meuble tiroir cuisine',
    category: 'storage',
    footprint: [1, 1],
    surfaceHeight: 0.85,
    visual: { type: 'kenney', model: 'kitchenCabinetDrawer', tint: '#F0A0B8' },
  },
  {
    id: 'pillow-coral',
    name: 'Coussin corail',
    category: 'soft',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'pillow', tint: '#F08070' },
  },
  {
    id: 'pillow-long-cream',
    name: 'Traversin crème',
    category: 'soft',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'pillowLong', tint: '#F5F0EA' },
  },
  {
    id: 'bed-double-blush',
    name: 'Lit double blush',
    category: 'beds',
    footprint: [3, 4],
    surfaceHeight: 0.62,
    visual: { type: 'kenney', model: 'bedDouble', tint: '#F0A0B8' },
  },
  {
    id: 'bear-honey',
    name: 'Ours miel',
    category: 'beds',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'bear', tint: '#C4894A' },
  },
  {
    id: 'box-open-play',
    name: 'Carton ouvert',
    category: 'storage',
    footprint: [1, 1],
    surfaceHeight: 0.28,
    visual: { type: 'kenney', model: 'cardboardBoxOpen', tint: '#F0C040' },
  },
  {
    id: 'lamp-round-floor',
    name: 'Lampadaire rond',
    category: 'decor',
    footprint: [1, 1],
    visual: { type: 'kenney', model: 'lampRoundFloor', tint: '#F5EDE0' },
  },
  {
    id: 'lamp-round-table',
    name: 'Lampe de table ronde',
    category: 'desks',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'lampRoundTable', tint: '#C9A66B' },
  },
  {
    id: 'table-dining-oak',
    name: 'Table à manger chêne',
    category: 'desks',
    footprint: [2, 1],
    surfaceHeight: 0.72,
    visual: { type: 'kenney', model: 'table', tint: '#D4B896' },
  },
  {
    id: 'table-glass-dining',
    name: 'Table verre',
    category: 'desks',
    footprint: [2, 1],
    surfaceHeight: 0.72,
    visual: { type: 'kenney', model: 'tableGlass', tint: '#E8F0F8' },
  },
  {
    id: 'tv-antenna',
    name: 'TV antenne rétro',
    category: 'decor',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'kenney', model: 'televisionAntenna', tint: '#F5F0EA' },
  },
  {
    id: 'sandbox-garden',
    name: 'Bac à sable',
    category: 'toys',
    footprint: [2, 2],
    outdoor: true,
    surfaceHeight: 0.22,
    visual: { type: 'primitive', kind: 'sandBox', tint: '#E8C070' },
  },
  {
    id: 'aquarium-sky',
    name: 'Aquarium ciel',
    category: 'decor',
    footprint: [1, 1],
    nestable: true,
    visual: { type: 'primitive', kind: 'aquarium', tint: '#7EC8E8' },
  },
]
