import type { CatalogItem } from './types'

export const CATALOG: CatalogItem[] = [
  {
    id: 'bed-twin',
    name: 'Twin Bed',
    category: 'beds',
    footprint: [2, 4],
    visual: { type: 'primitive', kind: 'bed', tint: '#B8D4E8' },
  },
  {
    id: 'bed-canopy',
    name: 'Canopy Bed',
    category: 'beds',
    footprint: [2, 4],
    visual: { type: 'primitive', kind: 'bed', tint: '#E8C8E0' },
  },
  {
    id: 'desk-simple',
    name: 'Simple Desk',
    category: 'desks',
    footprint: [2, 1],
    visual: { type: 'primitive', kind: 'desk', tint: '#D4C4A8' },
  },
  {
    id: 'chair-study',
    name: 'Study Chair',
    category: 'desks',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'chair', tint: '#C8D8E8' },
  },
  {
    id: 'lamp-floor',
    name: 'Floor Lamp',
    category: 'desks',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'lamp', tint: '#F0E8C8' },
  },
  {
    id: 'shelf-low',
    name: 'Low Shelf',
    category: 'storage',
    footprint: [2, 1],
    visual: { type: 'primitive', kind: 'shelf', tint: '#D8E0C8' },
  },
  {
    id: 'chest-toys',
    name: 'Toy Chest',
    category: 'storage',
    footprint: [2, 1],
    visual: { type: 'primitive', kind: 'chest', tint: '#E8D0B8' },
  },
  {
    id: 'wardrobe-tall',
    name: 'Tall Wardrobe',
    category: 'storage',
    footprint: [2, 1],
    visual: { type: 'primitive', kind: 'shelf', tint: '#C8D0E0' },
  },
  {
    id: 'toy-blocks',
    name: 'Building Blocks',
    category: 'toys',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'blocks', tint: '#F0C8D8' },
  },
  {
    id: 'toy-dollhouse',
    name: 'Dollhouse',
    category: 'toys',
    footprint: [2, 2],
    visual: { type: 'primitive', kind: 'toy', tint: '#E8C8D0' },
  },
  {
    id: 'rug-round',
    name: 'Round Rug',
    category: 'soft',
    footprint: [2, 2],
    visual: { type: 'primitive', kind: 'rug', tint: '#D8C8E8' },
  },
  {
    id: 'beanbag-pink',
    name: 'Pink Beanbag',
    category: 'soft',
    footprint: [2, 2],
    visual: { type: 'primitive', kind: 'beanbag', tint: '#F0C0D0' },
  },
  {
    id: 'plant-pot',
    name: 'Potted Plant',
    category: 'decor',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'plant', tint: '#C8E8C8' },
  },
  {
    id: 'mirror-stand',
    name: 'Standing Mirror',
    category: 'decor',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'mirror', tint: '#E0E8F0' },
  },
]
