import type { CatalogItem } from './types'

/** Louise photo-matched catalogue — footprints fit the 6×9 grid. */
export const CATALOG: CatalogItem[] = [
  {
    id: 'bed-louise',
    name: 'Lit Louise',
    category: 'beds',
    footprint: [2, 4],
    visual: { type: 'primitive', kind: 'bedLouise', tint: '#F5F0EA' },
  },
  {
    id: 'stitch-blue',
    name: 'Stitch bleu',
    category: 'beds',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'plush', tint: '#5B8FCF' },
  },
  {
    id: 'angel-pink',
    name: 'Angel rose',
    category: 'beds',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'plush', tint: '#F0A8C0' },
  },
  {
    id: 'desk-louise',
    name: 'Bureau Louise',
    category: 'desks',
    footprint: [2, 1],
    visual: { type: 'primitive', kind: 'deskLouise', tint: '#FAF8F5' },
  },
  {
    id: 'chair-swivel-white',
    name: 'Chaise pivotante',
    category: 'desks',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'chairSwivel', tint: '#F5F5F5' },
  },
  {
    id: 'lamp-rattan-gold',
    name: 'Lampe rotin doré',
    category: 'desks',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'lampRattan', tint: '#C9A66B' },
  },
  {
    id: 'bookshelf-oak',
    name: 'Bibliothèque chêne',
    category: 'storage',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'bookshelf', tint: '#D4B896' },
  },
  {
    id: 'wardrobe-oak',
    name: 'Armoire chêne',
    category: 'storage',
    footprint: [2, 1],
    visual: { type: 'primitive', kind: 'wardrobe', tint: '#D4B896' },
  },
  {
    id: 'trofast-low',
    name: 'Trofast bas',
    category: 'storage',
    footprint: [3, 1],
    visual: { type: 'primitive', kind: 'trofast', tint: '#E8D4B8' },
  },
  {
    id: 'chest-lego-white',
    name: 'Coffre Lego blanc',
    category: 'storage',
    footprint: [2, 1],
    visual: { type: 'primitive', kind: 'chest', tint: '#F8F8F6' },
  },
  {
    id: 'basket-wicker-pompom',
    name: 'Panier osier pompons',
    category: 'storage',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'basket', tint: '#C4A882' },
  },
  {
    id: 'basket-wicker-small',
    name: 'Petit panier osier',
    category: 'storage',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'basket', tint: '#B8956A' },
  },
  {
    id: 'dollhouse-white-grey',
    name: 'Maison de poupée',
    category: 'toys',
    footprint: [2, 1],
    visual: { type: 'primitive', kind: 'dollhouse', tint: '#F5F5F2' },
  },
  {
    id: 'lego-camper',
    name: 'Camping-car Lego',
    category: 'toys',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'legoCamper', tint: '#F0F0EE' },
  },
  {
    id: 'lego-cluster',
    name: 'Village Lego',
    category: 'toys',
    footprint: [2, 1],
    visual: { type: 'primitive', kind: 'legoCluster', tint: '#E8C8D0' },
  },
  {
    id: 'pirate-ship-black',
    name: 'Bateau pirate',
    category: 'toys',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'pirateShip', tint: '#2A2A2E' },
  },
  {
    id: 'camper-van-pink',
    name: 'Van rose',
    category: 'toys',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'camperVan', tint: '#F0A0B8' },
  },
  {
    id: 'rug-hopscotch-pink',
    name: 'Tapis marelle rose',
    category: 'soft',
    footprint: [2, 3],
    visual: { type: 'primitive', kind: 'rugHopscotch', tint: '#E8A0B0' },
  },
  {
    id: 'chair-rattan-child',
    name: 'Chaise rotin enfant',
    category: 'soft',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'chairRattan', tint: '#C9A66B' },
  },
  {
    id: 'lightbox-louise',
    name: 'Lightbox Louise',
    category: 'decor',
    footprint: [1, 1],
    visual: { type: 'primitive', kind: 'lightbox', tint: '#FAFAF8' },
  },
]
